---
- name: Generate DH Parameters with a size 2048 bits
  community.crypto.openssl_dhparam:
    path: /etc/haproxy/dhparam
    size: 2048

- name: Configure haproxy
  ansible.builtin.template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    lstrip_blocks: true
    owner: root
    group: root
    mode: '0644'
  notify: Reload haproxy service

- name: Enable and start haproxy service
  ansible.builtin.systemd_service:
    name: haproxy.service
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
...
