---
angie_autostart: false
angie_httpd_conf_backend:
  backend: |
    server {
      listen 443 default_server reuseport ssl;
      listen [::]:443 default_server reuseport ssl;
      http2 on;

      ssl_certificate     {{ angie_web_cert.cert_path }};
      ssl_certificate_key {{ angie_web_cert.key_path }};

      location / {
        deny all;
      }
    }
angie_httpd_conf: '{{ angie_httpd_conf_default | ansible.builtin.combine(
  angie_httpd_conf_status, angie_httpd_conf_backend )}}'
...
