---
angie_httpd_conf_backend:
  backend: |
    server {
      listen 443 default_server reuseport ssl;
      listen [::]:443 default_server reuseport ssl;
      http2 on;

      ssl_certificate     {{ angie_web_cert.cert_path }};
      ssl_certificate_key {{ angie_web_cert.key_path }};

      client_max_body_size 25m;

      location /static/ {
        alias /opt/netbox/netbox/static/;
      }

      location / {
        proxy_pass http://unix:/run/netbox.sock;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
angie_httpd_conf: '{{ angie_httpd_conf_default | ansible.builtin.combine(
  angie_httpd_conf_status, angie_httpd_conf_backend )}}'
...
