---
tls_certs_certs:
  - ca_content: '{{ lookup("ansible.builtin.file", etcd_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", etcd_ca_key_path) }}'
    cert_path: '{{ etcd_cert_path }}'
    key_path: '{{ etcd_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", etcd_peer_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", etcd_peer_ca_key_path) }}'
    cert_path: '{{ etcd_peer_cert_path }}'
    key_path: '{{ etcd_peer_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", patroni_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", patroni_ca_key_path) }}'
    cert_path: '{{ patroni_cert_path }}'
    key_path: '{{ patroni_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", pgsql_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", pgsql_ca_key_path) }}'
    cert_path: '{{ pgsql_cert_path }}'
    key_path: '{{ pgsql_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", redis_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", redis_ca_key_path) }}'
    cert_path: '{{ redis_cert_path }}'
    key_path: '{{ redis_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", web_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", web_ca_key_path) }}'
    cert_path: '{{ web_cert_path }}'
    key_path: '{{ web_key_path }}'
    not_after: '{{ web_cert_not_after }}'
    not_before: '{{ web_cert_not_before }}'

tls_certs_subject_alt_name:
  - 'DNS:{{ inventory_hostname_short }}'
  - 'DNS:localhost'
  - 'IP:{{ ip_address }}'
  - 'IP:192.168.56.51'
  - 'IP:192.168.56.52'
  - 'IP:192.168.56.53'
  - 'IP:127.0.0.1'
...
