---
pgbouncer_certs: []

pgbouncer_config: '{{ pgbouncer_config_default |
  ansible.builtin.combine(pgbouncer_config_override, recursive=True) }}'
pgbouncer_config_default:
  databases:
  users:
  pgbouncer:
    logfile: /var/log/postgresql/pgbouncer.log
    pidfile: /var/run/postgresql/pgbouncer.pid
    listen_addr: localhost
    listen_port: 6432
    unix_socket_dir: /var/run/postgresql
    auth_type: scram-sha-256
    auth_file: /etc/pgbouncer/userlist.txt
    auth_hba_file: /etc/pgbouncer/pg_hba.txt
    admin_users: pgbouncer
    stats_users: pgbouncer
    pool_mode: session
    max_client_conn: 100
    default_pool_size: 20
pgbouncer_config_override: {}

pgbouncer_userlist: {}
pgbouncer_pg_hba_conf: ''
...
