---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags: [redis_sentinel, redis_sentinel_install]

- name: Configure redis
  ansible.builtin.import_tasks: config.yml
  tags: [redis_sentinel, redis_sentinel_config]

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers
  tags: [redis_sentinel, redis_sentinel_config]
...
