---
- name: Restart netbox socket
  ansible.builtin.systemd_service:
    name: netbox.socket
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'

- name: Reload netbox service
  ansible.builtin.systemd_service:
    name: netbox.service
    state: reloaded
  ignore_errors: '{{ ansible_check_mode }}'

- name: Restart netbox-rq service
  ansible.builtin.systemd_service:
    name: netbox-rq.service
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'

- name: Restart netbox-housekeeping timer
  ansible.builtin.systemd_service:
    name: netbox-housekeeping.timer
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'
...
