---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags: [pgbouncer, pgbouncer_install]

- name: Import certs tasks
  ansible.builtin.import_role:
    name: tls_copy
    public: false
  vars:
    tls_copy_certs: '{{ pgbouncer_certs }}'
    tls_copy_key_owner: postgres
    tls_copy_notify: Reload pgbouncer service
  tags: [pgbouncer, pgbouncer_certs]

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags: [pgbouncer, pgbouncer_config]

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers
  tags: [pgbouncer, pgbouncer_certs, pgbouncer_config]
...
