---
redis_ca_cert_path: '{{ undef(hint="patroni_ca_cert_path") }}'
redis_cert_path: '{{ undef(hint="patroni_cert_path") }}'
redis_key_path: '{{ undef(hint="patroni_key_path") }}'
redis_cert:
  ca_path: /etc/redis/serverca.crt
  cert_path: /etc/redis/server.crt
  key_path: /etc/redis/server.key
  ca_content: '{{ lookup("ansible.builtin.file", redis_ca_cert_path) }}'
  cert_content: '{{ lookup("ansible.builtin.file", redis_cert_path) }}'
  key_content: '{{ lookup("ansible.builtin.file", redis_key_path) }}'

redis_tls_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384
  - DHE-RSA-CHACHA20-POLY1305
redis_tls_ciphersuites:
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256

# https://ssl-config.mozilla.org/ffdhe2048.txt
redis_dhparam: |
  -----BEGIN DH PARAMETERS-----
  MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
  +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
  87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
  YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
  7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
  ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
  -----END DH PARAMETERS-----

redis_password: '{{ undef(hint="redis_password") }}'

redis_conf: '{{ redis_conf_default |
  ansible.builtin.combine(redis_conf_override) }}'
redis_conf_default:
  bind: 127.0.0.1 -::1
  protected-mode: true
  # START https://ssl-config.mozilla.org/#server=redis
  port: 0
  tls-port: 6379
  tls-cluster: true
  tls-replication: true
  tls-cert-file: '{{ redis_cert.cert_path }}'
  tls-key-file: '{{ redis_cert.key_path }}'
  tls-ca-cert-file: '{{ redis_cert.ca_path }}'
  tls-protocols: '"TLSv1.2 TLSv1.3"'
  tls-prefer-server-ciphers: false
  tls-ciphers: '{{ redis_tls_ciphers | join(":") }}'
  tls-ciphersuites: '{{ redis_tls_ciphersuites | join(":") }}'
  tls-dh-params-file: /etc/redis/dhparam
  # END https://ssl-config.mozilla.org/#server=redis
  # START PASSWORD
  masterauth: '"{{ redis_password }}"'
  requirepass: '"{{ redis_password }}"'
  # END PASSWORD
  tcp-backlog: 511
  timeout: 0
  tcp-keepalive: 300
  daemonize: true
  supervised: auto
  pidfile: /run/redis/redis-server.pid
  loglevel: notice
  logfile: /var/log/redis/redis-server.log
  databases: 16
  always-show-logo: false
  set-proc-title: true
  proc-title-template: '"{title} {listen-addr} {server-mode}"'
  locale-collate: ""
  stop-writes-on-bgsave-error: true
  rdbcompression: true
  rdbchecksum: true
  dbfilename: dump.rdb
  rdb-del-sync-files: false
  dir: /var/lib/redis
  replica-serve-stale-data: true
  replica-read-only: true
  repl-diskless-sync: true
  repl-diskless-sync-delay: 5
  repl-diskless-sync-max-replicas: 0
  repl-diskless-load: disabled
  repl-disable-tcp-nodelay: false
  replica-priority: 100
  acllog-max-len: 128
  lazyfree-lazy-eviction: false
  lazyfree-lazy-expire: false
  lazyfree-lazy-server-del: false
  replica-lazy-flush: false
  lazyfree-lazy-user-del: false
  lazyfree-lazy-user-flush: false
  oom-score-adj: false
  oom-score-adj-values: 0 200 800
  disable-thp: true
  appendonly: false
  appendfilename: "appendonly.aof"
  appenddirname: "appendonlydir"
  appendfsync: everysec
  no-appendfsync-on-rewrite: false
  auto-aof-rewrite-percentage: 100
  auto-aof-rewrite-min-size: 64mb
  aof-load-truncated: true
  aof-use-rdb-preamble: true
  aof-timestamp-enabled: false
  slowlog-log-slower-than: 10000
  slowlog-max-len: 128
  latency-monitor-threshold: 0
  notify-keyspace-events: ""
  hash-max-listpack-entries: 512
  hash-max-listpack-value: 64
  list-max-listpack-size: -2
  list-compress-depth: 0
  set-max-intset-entries: 512
  set-max-listpack-entries: 128
  set-max-listpack-value: 64
  zset-max-listpack-entries: 128
  zset-max-listpack-value: 64
  hll-sparse-max-bytes: 3000
  stream-node-max-bytes: 4096
  stream-node-max-entries: 100
  activerehashing: true
  client-output-buffer-limit normal: 0 0 0
  client-output-buffer-limit replica: 256mb 64mb 60
  client-output-buffer-limit pubsub: 32mb 8mb 60
  hz: 10
  dynamic-hz: true
  aof-rewrite-incremental-fsync: true
  rdb-save-incremental-fsync: true
  jemalloc-bg-thread: true
redis_conf_override: {}
...
