---
- name: Create NetBox directory
  ansible.builtin.file:
    path: '{{ netbox_unarchive_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Unarchive NetBox archive
  ansible.builtin.unarchive:
    src: '{{ netbox_download_url }}'
    dest: '{{ netbox_unarchive_dir }}'
    creates: '{{ netbox_unarchive_dir }}/upgrade.sh'
    owner: root
    group: root
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Create NetBox symlink
  ansible.builtin.file:
    src: '{{ netbox_unarchive_dir }}'
    dest: '{{ netbox_dir }}'
    state: link
    owner: root
    group: root
...
